"""Added is_active

Revision ID: 4118260a6c95
Revises: 7506c7c231c5
Create Date: 2025-07-20 09:00:07.925697

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4118260a6c95"
down_revision = "7506c7c231c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=True, server_default="1"))
    op.create_index(op.f("ix_user_is_active"), "user", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_is_active"), table_name="user")
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###
